This is makeindex, version 2.15 [TeX Live 2012] (kpathsea + Thai support).
Scanning style file ./final thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file ./final thesis.acn....done (92 entries accepted, 0 rejected).
Sorting entries....done (637 comparisons).
Generating output file ./final thesis.acr....done (64 lines written, 0 warnings).
Output written in ./final thesis.acr.
Transcript written in ./final thesis.alg.
