This is makeindex, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file E:/Aftha/Docs/ICT 4001 - Research Project/public transportation/8. final thesis/finalThesis/TeX files/final thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file final thesis.acn....done (12 entries accepted, 0 rejected).
Sorting entries....done (45 comparisons).
Generating output file final thesis.acr....done (18 lines written, 0 warnings).
Output written in final thesis.acr.
Transcript written in final thesis.alg.
